#!/bin/bash -x
#
# This simple script builds the the application for Windows
# using a cross compiler.
#

# Build the image
docker build -t qt .

# Now extract the generated binary
docker run qt cat release/helloworld.exe >helloworld.exe
